Validate inputs

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -5,7 +5,7 @@ on:
       tag:
         type: string
         required: true
-        description: The name of the tag to release
+        description: The name of the tag to release (X.Y.Z)
 jobs:
   release:
     name: Release login-protector
@@ -15,6 +15,16 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: main
+      - name: Validate inputs
+        run: |
+          if [[ ! ${{ inputs.tag }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid tag format. Please use X.Y.Z"
+            exit 1
+          fi
+          if git rev-parse v${{ inputs.tag }} >/dev/null 2>&1; then
+              echo "Tag v${{ inputs.tag }} already exists"
+              exit 1
+          fi
       - uses: ./.github/actions/aqua
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
@@ -49,6 +59,7 @@ jobs:
             git push
           fi
           git tag -a v${{ inputs.tag }} -m "Release login-protector v${{ inputs.tag }}"
+          git push origin v${{ inputs.tag }}
       - name: Create release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
